# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-01 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0008_bigone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='name')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sessions', to='autodidact.Tag'),
        ),
    ]
