# Generated by Django 3.0.8 on 2020-07-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0011_clear_obsolete_cdns_from_pandocfields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagefile',
            name='page',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='programs',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='session',
            field=models.ForeignKey(help_text='You can move assignments between sessions by using this dropdown menu', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='autodidact.Session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='autodidact.Course'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageFile',
        ),
        migrations.DeleteModel(
            name='Programme',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
