# Generated by Django 2.2.4 on 2019-12-13 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0012_move_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='session',
            field=models.ForeignKey(help_text='You can move assignments between sessions by using this dropdown menu', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='autodidact.Session'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='autodidact.Course'),
        ),
    ]
