# Generated by Django 2.2.9 on 2020-02-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breadcrumbs',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.section',),
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['number'], 'verbose_name': 'section', 'verbose_name_plural': 'sections'},
        ),
    ]
