# Generated by Django 2.2.9 on 2020-02-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200207_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.section',),
        ),
    ]
