# Generated by Django 2.2.9 on 2020-02-28 09:07

import cms.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='section',
            name='button_text',
        ),
        migrations.AddField(
            model_name='section',
            name='href',
            field=cms.models.VarCharField(blank=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=cms.models.VarCharField(verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=cms.models.VarCharField(verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=cms.models.VarCharField(verbose_name='type'),
        ),
    ]
