# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-29 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autodidact', '0010_clear_obsolete_cdns_from_pandocfields'),
        ('uvt_user', '0006_populate_auth_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='uvtuser',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autodidact.Programme'),
        ),
    ]
