# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uvt_user', '0007_uvtuser_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uvtuser',
            name='programme',
        ),
    ]
